package org.waldo.demo.rules

import org.waldo.demo.foundation.pojo.Product

rule Offer4Diamond
    when
        productObject : Product(type == Product.DIAMOND)
    then
        productObject.setDiscount(15);
    end
rule Offer4Gold
    when
        productObject: Product(type == Product.GOLD)
    then
        productObject.setDiscount(25);
        update(productObject);
    end

rule level2
    when
      productObject: Product(discount == 25);
    then

     end
